### PR TITLE
fix http-axum example code

### PR DESCRIPTION
**Pull request by sn99**
*Issue #, if available:*
https://github.com/awslabs/aws-lambda-rust-runtime/pull/796

*Description of changes:*
Fix compilation error introduced in PR https://github.com/awslabs/aws-lambda-rust-runtime/pull/796

By submitting this pull request

- [x] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [x] I confirm that I've made a best effort attempt to update all relevant documentation.

### CODE REVIEW

**Review by greenwoodcm — APPROVED** [review]
@calavera think we should build examples as part of CI?

**Comment by bnusunny** [comment]
It does: "Check examples".
